### ISSUE TITLE
Install Parse Dashboard too

### ISSUE THREAD

**Issue by arielelkin** [instainer/parse-server-docker#4]

**Comment by peterwilli** [comment]
I dont think the parse dashboard is available locally.
Edit: Appearantly it is: https://github.com/ParsePlatform/parse-dashboard

**Comment by peterwilli** [comment]
@arielelkin I am currently working on a fork that includes dashboard as well as optional mongodb (in case you already have one)

It's being made here: https://github.com/CodeBuffet/parse-server-docker
I am trying to finish this today as I need it for myself as well

Edit: https://github.com/CodeBuffet/parse-server-docker it's here, I'm running it behind nginx as we speak.

Hope it helps more people!

**Comment by arielelkin** [comment]
@peterwilli looking good. 

Couple of things: 
- the mongodb database shouldn't be all inside a container.. I'd mount a volume onto it from the host, so that it persists if the container's killed. 
- support for push notifications is important... We need a place to insert our `p12` certificates.
